apiVersion: v1
kind: Pod
metadata:
  name: env-vars-01
spec:
  containers:
    - name: test
      image: rkalluru/learnk8s:rhel9-bare
      env:
        - name: URL
          value: google.com





# [ root@docker-vm ~/Devops/learn-kubernetes ]# kubectl apply -f 11.env-vars.yml
# pod/env-vars-01 created

# [ root@docker-vm ~/Devops/learn-kubernetes ]# kubectl exec -it env-vars-01 -- bash
# [root@env-vars-01 /]# env | grep -i url
# URL=google.com
