apiVersion: v1
kind: Secret
metadata:
  name: secret-demo
data:
  username: cmFnaHU=
  password: YWJjZEAxMjM=
---
apiVersion: v1
kind: Pod
metadata:
  name: secret-demo1
spec:
  containers:
    - name: demo
      image: rkalluru/learnk8s:rhel9-bare
      env:
        - name: username
          valueFrom:
            secretKeyRef:
              name: secret-demo
              key: username
---
apiVersion: v1
kind: Pod
metadata:
  name: secret-demo2
spec:
  containers:
    - name: demo
      image: rkalluru/learnk8s:rhel9-bare
      envFrom:
        - secretRef:
            name: secret-demo
---
apiVersion: v1
kind: Pod
metadata:
  name: secret-demo3
spec:
  containers:
    - name: demo
      image: rkalluru/learnk8s:rhel9-bare
      volumeMounts:
      - name: config
        mountPath: "/config"
        readOnly: true
  volumes:
  - name: config
    secret:
      secretName: secret-demo



# [ root@docker-vm ~/Devops/learn-kubernetes ]# kubectl exec -it pod/secret-demo1 -- bash
# [root@secret-demo1 /]# env | grep username
# username=raghu

# [ root@docker-vm ~/Devops/learn-kubernetes ]# kubectl exec -it pod/secret-demo2 -- bash
# [root@secret-demo2 /]# env | grep username
# username=raghu
# [root@secret-demo2 /]# env | grep password
# password=abcd@123

# [ root@docker-vm ~/Devops/learn-kubernetes ]# kubectl exec -it pod/secret-demo3 -- bash
# [root@secret-demo3 /]# cd /config
# [root@secret-demo3 config]# ls
# password  username
# [root@secret-demo3 config]# env |grep username
# [root@secret-demo3 config]# cat  username
# raghu[root@secret-demo3 config]# ls

